// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfgY9Mhv3q2G8BaAVxrSarCeH25E41iUk',
    appId: '1:364286584521:web:1be9da1a46e468c8d48f18',
    messagingSenderId: '364286584521',
    projectId: 'takecareofmywallet',
    authDomain: 'takecareofmywallet.firebaseapp.com',
    storageBucket: 'takecareofmywallet.firebasestorage.app',
    measurementId: 'G-M3J0JVPPHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7tdmj_lwEPZv_GjaOq4TQveD0d8eoY-k',
    appId: '1:364286584521:android:b04bc16bac06186cd48f18',
    messagingSenderId: '364286584521',
    projectId: 'takecareofmywallet',
    storageBucket: 'takecareofmywallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNSX89k1o3NW3JicP4ozpRcKmMxGpUgkU',
    appId: '1:364286584521:ios:cc6525e78d8ad5f0d48f18',
    messagingSenderId: '364286584521',
    projectId: 'takecareofmywallet',
    storageBucket: 'takecareofmywallet.firebasestorage.app',
    iosClientId: '364286584521-bo36fkin7ae0ai604ar71q68429mi9as.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNSX89k1o3NW3JicP4ozpRcKmMxGpUgkU',
    appId: '1:364286584521:ios:cc6525e78d8ad5f0d48f18',
    messagingSenderId: '364286584521',
    projectId: 'takecareofmywallet',
    storageBucket: 'takecareofmywallet.firebasestorage.app',
    iosClientId: '364286584521-bo36fkin7ae0ai604ar71q68429mi9as.apps.googleusercontent.com',
    iosBundleId: 'com.example.saveWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfgY9Mhv3q2G8BaAVxrSarCeH25E41iUk',
    appId: '1:364286584521:web:3db78f4c19da1a31d48f18',
    messagingSenderId: '364286584521',
    projectId: 'takecareofmywallet',
    authDomain: 'takecareofmywallet.firebaseapp.com',
    storageBucket: 'takecareofmywallet.firebasestorage.app',
    measurementId: 'G-XJLLJKG1WV',
  );

}